### ISSUE TITLE
4.48.0 regression test failure

### ISSUE THREAD

**Issue by chenrui333** [firecow/gitlab-ci-local#1187]
👋 trying to build the latest release, but run into some regression test issue. The error log is as below:

<details>
<summary>error build log</summary>

```
$ /opt/homebrew/Cellar/gitlab-ci-local/4.48.0/bin/gitlab-ci-local --list
Error: Cannot find module './schema.json'
Require stack:
- /opt/homebrew/Cellar/gitlab-ci-local/4.48.0/libexec/lib/node_modules/gitlab-ci-local/src/schema/index.js
- /opt/homebrew/Cellar/gitlab-ci-local/4.48.0/libexec/lib/node_modules/gitlab-ci-local/src/validator.js
- /opt/homebrew/Cellar/gitlab-ci-local/4.48.0/libexec/lib/node_modules/gitlab-ci-local/src/parser.js
- /opt/homebrew/Cellar/gitlab-ci-local/4.48.0/libexec/lib/node_modules/gitlab-ci-local/src/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1028:15)
    at Function.Module._load (node:internal/modules/cjs/loader:873:27)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/opt/homebrew/Cellar/gitlab-ci-local/4.48.0/libexec/lib/node_modules/gitlab-ci-local/src/schema/index.ts:2:16)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/8738385082/job/23977555195
relates to Homebrew/homebrew-core#169393

**Comment by firecow** [comment]
I think we failed to include schema.json into the binaries. 4.48.1 coming up.

**Comment by chenrui333** [comment]
cool, cool, thanks!

**Comment by chenrui333** [comment]
still does not work

```
==> /opt/homebrew/Cellar/gitlab-ci-local/4.48.1/bin/gitlab-ci-local --list
Error: Cannot find module './schema.json'
Require stack:
- /opt/homebrew/Cellar/gitlab-ci-local/4.48.1/libexec/lib/node_modules/gitlab-ci-local/src/schema/index.js
- /opt/homebrew/Cellar/gitlab-ci-local/4.48.1/libexec/lib/node_modules/gitlab-ci-local/src/validator.js
- /opt/homebrew/Cellar/gitlab-ci-local/4.48.1/libexec/lib/node_modules/gitlab-ci-local/src/parser.js
- /opt/homebrew/Cellar/gitlab-ci-local/4.48.1/libexec/lib/node_modules/gitlab-ci-local/src/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1028:15)
    at Function.Module._load (node:internal/modules/cjs/loader:873:27)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/opt/homebrew/Cellar/gitlab-ci-local/4.48.1/libexec/lib/node_modules/gitlab-ci-local/src/schema/index.ts:2:16)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)

/opt/homebrew/Library/Homebrew/ignorable.rb:29:in `block in raise'
Minitest::Assertion: Expected: 0
  Actual: 1
```

**Comment by chenrui333** [comment]
can you maybe try adding this in the package.json?

```
  "files": [
    "src/schema/schema.json"
  ],
```

**Comment by tchernomax** [comment]
@firecow I can confirm that 4.48.1 **doesn't** work.

**Comment by pineapplehunter** [comment]
Hi, I was having this issue.
Adding this to package.json seems to work for me.

```
  "files":[
    "src/**/*.js",
    "src/**/*.json"
  ]
```

I was able to print the files included by running this command.

```shell
$ npm pack --dry-run --json | jq ".[].files[].path" -r
```

**Comment by firecow** [comment]
I'm releasing 4.48.2 now

**Comment by chenrui333** [comment]
works for me per https://github.com/Homebrew/homebrew-core/pull/169824
