### ISSUE TITLE
chown error when using template Code-Quality.gitlab-ci.yml on Podman

### ISSUE THREAD

**Issue by sffortytwo** [firecow/gitlab-ci-local#1246]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
include:
- template: Code-Quality.gitlab-ci.yml
```

**Error output**
```
❯ gitlab-ci-local
parsing and downloads finished in 63 ms
json schema validated in 162 ms
code_quality starting docker:20.10.12 (test)
Error: Command failed with exit code 1: docker start --attach 3cba56bb563c38c275a0444d99d194c2d421cd67bc4d87b75021f04518df55d9
chown: missing operand
Try 'chown --help' for more information.
    at makeError (/mnt/c/Users/jzaayman/AppData/Roaming/npm/node_modules/gitlab-ci-local/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/mnt/c/Users/jzaayman/AppData/Roaming/npm/node_modules/gitlab-ci-local/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Job.start (/mnt/c/Users/jzaayman/AppData/Roaming/npm/node_modules/gitlab-ci-local/src/job.ts:479:13)
    at /mnt/c/Users/jzaayman/AppData/Roaming/npm/node_modules/gitlab-ci-local/node_modules/p-map/index.js:57:22
```

**Expected behavior**
https://gitlab.lelyonline.com/common/cm/images/-/jobs/12383164

**Host information**
Ubuntu 22.04.4
gitlab-ci-local 4.50.0

**Containerd binary**
podman 3.4.4

**Additional context**
Running Ubuntu under WSL on Windows 10 (19045.4412)

**Comment by firecow** [comment]
Closing as stale. This was reported on v4.50.0 with no follow-up. If this still occurs on the latest version with Podman, please reopen with updated reproduction steps.
