### ISSUE TITLE
Network handling for `services` with podman failing since `4.50.0`

### ISSUE THREAD

**Issue by skuethe** [firecow/gitlab-ci-local#1300]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
job:
  services:
    - name: docker.io/library/busybox
  script:
      - echo "Heya"
```

**Expected behavior**
```bash
$ gitlab-ci-local --version
4.49.0

$ gitlab-ci-local --container-executable podman
parsing and downloads finished in 36 ms
job starting shell (test)
job started service image: docker.io/library/busybox:latest with aliases: docker.io-library-busybox, docker.io__library__busybox in 230 ms
job Could not find exposed tcp ports docker.io/library/busybox:latest
job $ echo "Heya"
job > Heya
job finished in 386 ms

 PASS  job
pipeline finished in 483 ms
```

**Host information**
Fedora 39 (podman out of the box)
gitlab-ci-local 4.49.0 (working)
gitlab-ci-local 4.50.0 and later (not working)

**Containerd binary**
podman (rootless)

```bash
$ podman --version
podman version 4.9.4
```

**Additional context**
Probably related to this PR:
https://github.com/firecow/gitlab-ci-local/pull/1226

Searching for this error it seems that this happens when trying to connect a "slirp4netns" network with other networks (bridged).

Error with `4.50.0`:
```bash
$ gitlab-ci-local-4.50.0 --version
4.50.0

$ gitlab-ci-local-4.50.0 --container-executable podman
parsing and downloads finished in 39 ms
json schema validated in 127 ms
job starting shell (test)
Error: Command failed with exit code 125: podman network connect --alias docker.io-library-busybox --alias docker.io__library__busybox gitlab-ci-local-612717 c1fd44cf33acccf90f7fb65ccdb4522038061c7bc8202c14632a04e5952cace1
Error: "slirp4netns" is not supported: invalid network mode
    at makeError (/snapshot/firecow-gitlab-ci-local/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/snapshot/firecow-gitlab-ci-local/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Job.startService (/snapshot/firecow-gitlab-ci-local/src/job.ts:1214:9)
    at /snapshot/firecow-gitlab-ci-local/src/job.ts:492:48
    at async Promise.all (index 0)
    at Job.start (/snapshot/firecow-gitlab-ci-local/src/job.ts:488:13)
    at /snapshot/firecow-gitlab-ci-local/node_modules/p-map/index.js:57:22
```

Error with `4.52.1`:
```bash
$ gitlab-ci-local-4.52.1 --version
4.52.1

$ gitlab-ci-local-4.52.1 --container-executable podman
parsing and downloads finished in 36 ms.
json schema validated in 124 ms
job starting shell (test)
Error: Command failed with exit code 125: podman network connect --alias docker.io-library-busybox --alias docker.io__library__busybox gitlab-ci-local-987234 d7494b584648b6abf7af4e883d8f5c5713069ddcbba0b8e2d8b023e44b314501
Error: "slirp4netns" is not supported: invalid network mode
    at makeError (/snapshot/firecow-gitlab-ci-local/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/snapshot/firecow-gitlab-ci-local/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Job.startService (/snapshot/firecow-gitlab-ci-local/src/job.ts:1226:9)
    at /snapshot/firecow-gitlab-ci-local/src/job.ts:502:48
    at async Promise.all (index 0)
    at Job.start (/snapshot/firecow-gitlab-ci-local/src/job.ts:498:13)
    at /snapshot/firecow-gitlab-ci-local/node_modules/p-map/index.js:57:22
```

Also happens when explicitly specifying a network via `--network`:
```bash
$ podman network ls
NETWORK ID    NAME                    DRIVER
fe4352b37add  gitlab-ci-local-175683  bridge
3b01fc9b2ad0  gitlab-ci-local-250057  bridge
6606a433a279  gitlab-ci-local-300890  bridge
2f259bab93aa  podman                  bridge

$ gitlab-ci-local-4.52.1 --container-executable podman --network podman
parsing and downloads finished in 32 ms.
json schema validated in 127 ms
job starting shell (test)
Error: Command failed with exit code 125: podman network connect --alias docker.io-library-busybox --alias docker.io__library__busybox gitlab-ci-local-621822 d3da19d43938d09c10313d83b9f4b5f15eae6ec9396b7c2e093b183b81bb44f1
Error: "slirp4netns" is not supported: invalid network mode
    at makeError (/snapshot/firecow-gitlab-ci-local/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/snapshot/firecow-gitlab-ci-local/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Job.startService (/snapshot/firecow-gitlab-ci-local/src/job.ts:1226:9)
    at /snapshot/firecow-gitlab-ci-local/src/job.ts:502:48
    at async Promise.all (index 0)
    at Job.start (/snapshot/firecow-gitlab-ci-local/src/job.ts:498:13)
    at /snapshot/firecow-gitlab-ci-local/node_modules/p-map/index.js:57:22
```

**Comment by skuethe** [comment]
Having a quick look at the code changes, can it be that the actual service container is not started as part of the `gitlab-ci-local-${this.jobId}` network?

https://github.com/firecow/gitlab-ci-local/pull/1226/files#diff-a66bffdb979d130e04df61edb944cc04d2fdedf8117ca2732cb6d119d5f5e7b2L1131-R1141

**Comment by PigeonF** [comment]
For debugging, essentially the following steps happen

```console
$ podman network create gitlab-ci-local-323838
$ podman create --interactive docker.io/library/busybox:latest
db9f7658884862197303c4249ce008e52264de4a30bf95e0284a491b4a662cb0
$ podman network connect --alias docker.io-library-busybox --alias docker.io__library__busybox gitlab-ci-local-323838 db9f7658884862197303c4249ce008e52264de4a30bf95e0284a491b4a662cb0
```

I will take a look, but I recall that the last time I looked at this (the changeset you linked above) there might be some differences between docker and podman in how they handle networks.

**Comment by skuethe** [comment]
I did a quick test locally. If I re-add `--network gitlab-ci-local-${this.jobId}` to the `startService` -> `let dockerCmd` instructions and build the binary it works again.

**Comment by PigeonF** [comment]
Looking at <https://github.com/containers/podman/issues/19577>, the issue seems to be that the service container is created with the default network mode (in your case `slirp4netns`, when reproducing this locally my network mode is `pasta`). It seems the fix is to start the service container in `bridge` mode or by directly connecting to the `gitlab-ci-local-323838` network.

**Comment by skuethe** [comment]
And that was the behavour before, right?
Was there a specific reason to not create the job container within the "gitlab-ci-local-.." network?

**Comment by PigeonF** [comment]
I don't recall exactly, but I think the reason is that you cannot use user defined networks if you also specify `host` network for example.

I will push a fix in a minute, but let me gather some documentation so that in the future I don't have to remember why I did things the way I did.

**Comment by PigeonF** [comment]
## Docker

```console
$ docker --version
Docker version 24.0.9, build v24.0.9
$ docker network create gitlab-ci-local-123
```

### Without `--network`

```console
$ docker create --interactive --name without-network docker.io/library/busybox:latest
$ docker network connect --alias docker.io-library-busybox gitlab-ci-local-123 without-network
```

### With `--network=bridge`

```console
$ docker create --interactive --name with-network-bridge --network=bridge docker.io/library/busybox:latest
$ docker network connect --alias docker.io-library-busybox gitlab-ci-local-123 with-network-bridge
```

### With `--network=bridge`, `--network=gitlab-ci-local-123`

```console
$ docker create --interactive --network=bridge --network=gitlab-ci-local-123 docker.io/library/busybox:latest
docker: conflicting options: cannot attach both user-defined and non-user-defined network-modes.
See 'docker create --help'.
```

## Podman

```console
$ podman --version
podman version 5.0.3
$ podman network create gitlab-ci-local-123
```

### Without `--network`

```console
$ podman create --interactive --name without-network docker.io/library/busybox:latest
$ podman network connect --alias docker.io-library-busybox gitlab-ci-local-123 without-network
Error: "pasta" is not supported: invalid network mode
```

### With `--network=bridge`

```console
$ podman create --interactive --name with-network-bridge --network=bridge docker.io/library/busybox:latest
$ podman network connect --alias docker.io-library-busybox gitlab-ci-local-123 with-network-bridge
```

### With `--network=bridge`, `--network=gitlab-ci-local-123`

```console
$ podman create --interactive --network=bridge --network=gitlab-ci-local-123 docker.io/library/busybox:latest
```

**Comment by PigeonF** [comment]
@skuethe can you check if https://github.com/firecow/gitlab-ci-local/pull/1301 fixes the problem for you?

**Comment by skuethe** [comment]
> can you check if #1301 fixes the problem for you?

It does fix the problem! Thank you for the quick feedback and fix:

```bash
$ ~/git/github/firecow/gitlab-ci-local/bin/linux/gitlab-ci-local --container-executable podman
parsing and downloads finished in 37 ms.
json schema validated in 141 ms
job starting shell (test)
job started service image: docker.io/library/busybox:latest with aliases: docker.io-library-busybox, docker.io__library__busybox in 225 ms
job Could not find exposed tcp ports docker.io/library/busybox:latest
job $ echo "Heya"
job > Heya
job finished in 383 ms

 PASS  job
pipeline finished in 631 ms
```



> One workaround that should work for you without any patches for now is to run with --network bridge

This actually does not work. I tried doing that, but it still breaks:

```bash
$ gitlab-ci-local-4.52.1 --container-executable podman --network bridge
parsing and downloads finished in 44 ms.
json schema validated in 128 ms
job starting shell (test)
Error: Command failed with exit code 125: podman network connect --alias docker.io-library-busybox --alias docker.io__library__busybox gitlab-ci-local-916989 e52d3c427e0b0cb2e7d3333e8ccfa4c396341a358b521d0792d1d31f31363bb7
Error: "slirp4netns" is not supported: invalid network mode
    at makeError (/snapshot/firecow-gitlab-ci-local/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/snapshot/firecow-gitlab-ci-local/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Job.startService (/snapshot/firecow-gitlab-ci-local/src/job.ts:1226:9)
    at /snapshot/firecow-gitlab-ci-local/src/job.ts:502:48
    at async Promise.all (index 0)
    at Job.start (/snapshot/firecow-gitlab-ci-local/src/job.ts:498:13)
    at /snapshot/firecow-gitlab-ci-local/node_modules/p-map/index.js:57:22

```
