### ISSUE TITLE
Error response from daemon

### ISSUE THREAD

**Issue by mansto** [firecow/gitlab-ci-local#1361]
**Expected behavior**
if i run the command gitlab-ci-local i always get the following error:
```
Error response from daemon: the working directory 'C:/Program Files/Git/gcl-builds' is invalid, it needs to be an absolute path
    at makeError (C:\snapshot\firecow-gitlab-ci-local\node_modules\execa\lib\error.js:60:11)
    at handlePromise (C:\snapshot\firecow-gitlab-ci-local\node_modules\execa\index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Job.execScripts (C:\snapshot\firecow-gitlab-ci-local\src\job.ts:805:43)
    at Job.execPreScripts (C:\snapshot\firecow-gitlab-ci-local\src\job.ts:641:36)
    at Job.start (C:\snapshot\firecow-gitlab-ci-local\src\job.ts:538:9)
    at C:\snapshot\firecow-gitlab-ci-local\node_modules\p-map\index.js:57:22
```

Is there a way to change the path for the working dir?

**Host information**
Ubuntu
gitlab-ci-local 4.53.0

**Containerd binary**
using rancher /dockerd on win11

**Comment by mansto** [comment]
Ok. Thank you very much for the quick feedback. I am closing the issue.
