### ISSUE TITLE
Ability to ignore specific files/folders/symlinks 

### ISSUE THREAD

**Issue by Algomorph** [firecow/gitlab-ci-local#1425]
**Is your feature request related to a problem? Please describe.**

Yes. Part of the project I'm working on is using Bazel, and hence Bazel IDE plugin(s), which -- only on the developer's machine -- tend to write symlinks to the home directory. These link to system files that `gitlab-ci-local` doesn't have the permissions to read, which is a very common situation if the Bazel build is referencing system files/folders.

That is, when I run `gitlab-ci-local --list` I'm seeing:
```
Error: EACCES: permission denied, scandir '/home/greg/Builds/physiology/edge/bazel-edge/external/linux_opencv/share/mblinux'
    at Object.readdirSync (node:fs:1507:26)
    at Object.readdirSync (pkg/prelude/bootstrap.js:1306:35)
    at readdirWithFileTypes (/snapshot/firecow-gitlab-ci-local/node_modules/@nodelib/fs.scandir/out/providers/sync.js:16:33)
    at Object.Bq (/snapshot/firecow-gitlab-ci-local/node_modules/@nodelib/fs.scandir/out/providers/sync.js:10:16)
    at Sp.Kq (/snapshot/firecow-gitlab-ci-local/node_modules/@nodelib/fs.scandir/out/index.js:18:17)
    at Sp._handleDirectory (/snapshot/firecow-gitlab-ci-local/node_modules/@nodelib/fs.walk/out/readers/sync.js:28:34)
    at Sp._handleQueue (/snapshot/firecow-gitlab-ci-local/node_modules/@nodelib/fs.walk/out/readers/sync.js:23:18)
    at Sp.read (/snapshot/firecow-gitlab-ci-local/node_modules/@nodelib/fs.walk/out/readers/sync.js:15:14)
    at kp.read (/snapshot/firecow-gitlab-ci-local/node_modules/@nodelib/fs.walk/out/providers/sync.js:11:29)
    at rd.wD (/snapshot/firecow-gitlab-ci-local/node_modules/@nodelib/fs.walk/out/index.js:20:21)
```

**Describe the solution you'd like**
Either an `--exclude-from-scan` CLI argument, an `EXCLUDE_FROM_SCAN` variable that can be set in .gitlab-ci-local/.env (or the like), or (better) both.

**Describe alternatives you've considered**
I'm currently wrapping gitlab-ci-local with the following script (that temporarily removes the IDE-generated symlink `edge/bazel-edge`):
```
#!/bin/bash

# Read the target of the symlink and store it in a file
link_target=$(readlink edge/bazel-edge)
echo "$link_target" > .edge-link-target

# Remove the symlink
rm edge/bazel-edge

# Run gitlab-ci-local with the original arguments
gitlab-ci-local "$@"

# Restore the symlink regardless of the exit status
ln -s "$link_target" edge/bazel-edge

# Remove the temporary file
rm .edge-link-target
```

**Comment by ANGkeith** [comment]
can't really replicate it.. 

could you provide a minimal way to replicating the issue ?

**Comment by Algomorph** [comment]
@ANGkeith thanks for looking into this. I've been trying real hard for about an hour now to replicate the link / directory structure to make a simple project fail, but so far I've failed to do so. The monorepo we're experiencing this on is way-too-large and way-too-proprietary for me to be able to share anything from there, but perhaps you have some insights about which cases `/snapshot/firecow-gitlab-ci-local/node_modules/@nodelib/fs.walk/out/index.js:20:21` from the trace above would be run?

**Comment by ANGkeith** [comment]
sure np, will take a look if i have spare time, 

but won't be too high prior, since you have a work around and we could'nt really replicate the issue yet

**Comment by firecow** [comment]
Closing as this could not be reproduced with a minimal example. The reported workaround (removing/restoring Bazel symlinks before/after runs) addresses the immediate need. If someone can provide a minimal reproduction, please open a new issue.
