### ISSUE TITLE
Permission denied when save cache from docker to the local path

### ISSUE THREAD

**Issue by netaskd** [firecow/gitlab-ci-local#1449]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
job:
  script:
    - go mod download
    - go build -v -trimpath -o "${ARTIFACTS_PATH}" ./
```

**Host information**
Ubuntu bookworm/sid
gitlab-ci-local 4.56.0 from deb

**Containerd binary**
Docker version 27.3.1, build ce12230

**Additional context**

```
/usr/local/bin/gitlab-ci-local job
```
also as 
```
/usr/local/bin/gitlab-ci-local --mount-cache=false job
```
produce the error, after build finished:

```
...
job finished in 1.25 min
Error: Command failed with exit code 1: docker cp 39c59120e52ea8e1755e092f09d3df4cfcd9fdc7302c05e055ccfd46c45e5f37:/cache/. .gitlab-ci-local/cache/.
mkdir /home/user/projects/docs/docs/portal/.gitlab-ci-local/cache/portal/.go/pkg/mod/contrib.go.opencensus.io/exporter/jaeger@v0.2.1/.github: permission denied
    at makeError (/snapshot/firecow-gitlab-ci-local/node_modules/execa/lib/error.js:60:11)
    at <anonymous> (/snapshot/firecow-gitlab-ci-local/node_modules/execa/index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Ut.copyOut (/snapshot/firecow-gitlab-ci-local/src/job.ts:1211:13)
    at async <anonymous> (/snapshot/firecow-gitlab-ci-local/src/job.ts:1118:21)
    at async Function.exclusive (/snapshot/firecow-gitlab-ci-local/src/mutex.ts:19:9)
    at async Ut.copyCacheOut (/snapshot/firecow-gitlab-ci-local/src/job.ts:1117:17)
    at async Ut.start (/snapshot/firecow-gitlab-ci-local/src/job.ts:601:9)
    at async <anonymous> (/snapshot/firecow-gitlab-ci-local/node_modules/p-map/index.js:57:22)
 ```

the destination directory does not have the write bit:
```
ls -ld /home/user/projects/docs/docs/portal/.gitlab-ci-local/cache/portal/.go/pkg/mod/contrib.go.opencensus.io/exporter/jaeger@v0.2.1/

dr-xr-xr-x 2 user user 4096 dec 5 15:54 /home/user/projects/docs/docs/portal/.gitlab-ci-local/cache/portal/.go/pkg/mod/contrib.go.opencensus.io/exporter/jaeger@v0.2.1/
```

The version gitlab-ci-local 4.55.0 does not create `.gitlab-ci-local/cache` and works perfect.

Also gitlab-ci-local 4.56.0
```
/usr/local/bin/gitlab-ci-local --mount-cache=true job 
```
does not create cache and forks perfect.

**Comment by pklapperich** [comment]
I'm having this same problem on Windows. I've only gotten `gitlab-ci-local` working in gitbash; from `cmd` and `powershell` it never starts the docker containers.

with `--mount-cache=true` there's no errors and no cache created. 

without `--mount-cache=true` it tries to copy from the cache and fails because it can't create symlinks on windows. I think gitlab-ci-local could work around this by creating a tar archive of the folder to cache and then copy the tar out, [as suggested here.](https://stackoverflow.com/a/78429961)

```
install > zxcvbn
install finished in 3.73 min
Error: Command failed with exit code 1: docker cp 01a08a5af49c68db1d40527c0d34e3afdfd06979ee3611760598f479c3b56685:/cache/. .gitlab-ci-local/cache/.
symlink ..\acorn\bin\acorn C:\projects\myproject\app\.gitlab-ci-local\cache\default\node_modules\.bin\acorn: A required privilege is not held by the client.
    at makeError (C:\Users\paul.klapperich\AppData\Local\nvs\node\20.18.1\x64\node_modules\gitlab-ci-local\node_modules\execa\lib\error.js:60:11)
    at handlePromise (C:\Users\paul.klapperich\AppData\Local\nvs\node\20.18.1\x64\node_modules\gitlab-ci-local\node_modules\execa\index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Job.copyOut (file:///C:/Users/paul.klapperich/AppData/Local/nvs/node/20.18.1/x64/node_modules/gitlab-ci-local/src/job.js:1010:13)
    at async file:///C:/Users/paul.klapperich/AppData/Local/nvs/node/20.18.1/x64/node_modules/gitlab-ci-local/src/job.js:923:21
    at async Mutex.exclusive (file:///C:/Users/paul.klapperich/AppData/Local/nvs/node/20.18.1/x64/node_modules/gitlab-ci-local/src/mutex.js:16:9)
    at async Job.copyCacheOut (file:///C:/Users/paul.klapperich/AppData/Local/nvs/node/20.18.1/x64/node_modules/gitlab-ci-local/src/job.js:922:17)
    at async Job.start (file:///C:/Users/paul.klapperich/AppData/Local/nvs/node/20.18.1/x64/node_modules/gitlab-ci-local/src/job.js:461:9)
    at async C:\Users\paul.klapperich\AppData\Local\nvs\node\20.18.1\x64\node_modules\gitlab-ci-local\node_modules\p-map\index.js:57:22
```

**Comment by netaskd** [comment]
duplicate #1170
