### ISSUE TITLE
git config didn't provide valid matches

### ISSUE THREAD

**Issue by ck-trigfb** [firecow/gitlab-ci-local#184]
First of all big thanks for fixing my previous issues that fast. Nice.

If i now start the current version from master i get an error: "git config didn't provide valid matches"
I already figured out, that the regex for matching the url in git config don't match for my config file. If have the string
url = https://github.com/firecow/gitlab-ci-local.git
and the regex in parser.ts expects at least one "@" inside the url
`/url = .*@(?<domain>.*?)[:|/](?<group>.*)\/(?<project>.*)\.git/`

Fix for me: I have changed the regex to something like this:
`url = .*:\/\/@?(?<domain>.*?)[:|/](?<group>.*)\/(?<project>.*)\.git`

**Comment by firecow** [comment]
@ck-trigfb Can you send me the entire context of your `cat .git/config`

**Comment by ck-trigfb** [comment]
`cat .git/config ` ->
```
[core]
        repositoryformatversion = 0
        filemode = false
        bare = false
        logallrefupdates = true
        symlinks = false
        ignorecase = true
[remote "origin"]
        url = https://github.com/firecow/gitlab-ci-local.git
        fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
        remote = origin
        merge = refs/heads/master
[branch "chmod-bugfix"]
        remote = origin
        merge = refs/heads/chmod-bugfix
```

**Comment by firecow** [comment]
Can you provide me with the git config for the project that throws the "git config didn't provide valid matches"
```
cd work/myproject/
cat .git/config
```

**Comment by firecow** [comment]
Can you provide me with the git config for the project that throws the "git config didn't provide valid matches"
```
cd work/myproject/
cat .git/config
```
@ck-trigfb

**Comment by ck-trigfb** [comment]
`[core]
        repositoryformatversion = 0
        filemode = false
        bare = false
        logallrefupdates = true
        symlinks = false
        ignorecase = true
[remote "origin"]
        url = https://gitlab.com/trigfb/ctd/tdms.git
        fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
        remote = origin
        merge = refs/heads/master`

**Comment by firecow** [comment]
@ck-trigfb Can you try latest master please...

**Comment by ck-trigfb** [comment]
```
node:internal/bootstrap/switches/does_own_process_state:126
    cachedCwd = rawMethods.cwd();
                           ^

Error: ENOENT: no such file or directory, uv_cwd
    at process.wrappedCwd (node:internal/bootstrap/switches/does_own_process_state:126:28)
    at Object.process.cwd (/mnt/wsl/docker-desktop-bind-mounts/Ubuntu/7345dc52fec8989100057833ff06f29786db0459c668f06d2ecf30ef0f408d55/node_modules/graceful-fs/polyfills.js:10:19)
    at oe.Yargs (/mnt/wsl/docker-desktop-bind-mounts/Ubuntu/7345dc52fec8989100057833ff06f29786db0459c668f06d2ecf30ef0f408d55/node_modules/yargs/build/index.cjs:1:55554)
    at Argv (/mnt/wsl/docker-desktop-bind-mounts/Ubuntu/7345dc52fec8989100057833ff06f29786db0459c668f06d2ecf30ef0f408d55/node_modules/yargs/index.cjs:12:16)
    at Object.<anonymous> (/mnt/wsl/docker-desktop-bind-mounts/Ubuntu/7345dc52fec8989100057833ff06f29786db0459c668f06d2ecf30ef0f408d55/node_modules/yargs/index.cjs:7:1)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'uv_cwd'
}
```
