### ISSUE TITLE
Empty state file gives error

### ISSUE THREAD

**Issue by moberghammer** [firecow/gitlab-ci-local#25]
gitlab-ci-local 
gitlab-ci-local [job]
Runs the entire pipeline or a single [job]
Positionals:
  job  Jobname to execute                                               [string]
Options:
  --help        Show help                                              [boolean]
  --version     Show version number                                    [boolean]
  --manual      One or more manual jobs to run during a pipeline         [array]
  --list        List jobs and job information                           [string]
  --cwd         Path to a gitlab-ci.yml                                 [string]
  --completion  Generate bash completion script                         [string]
  --needs       Run needed jobs, when executing a single job           [boolean]
TypeError: Cannot read property 'pipelineIid' of undefined
    at Object.incrementPipelineIid (/snapshot/gitlab-ci-local/dist/predefined_variables.js)
    at Object.handler (/snapshot/gitlab-ci-local/dist/default_cmd.js)
    at Object.runCommand (/snapshot/gitlab-ci-local/node_modules/yargs/lib/command.js:240:40)
    at Object.parseArgs [as _parseArgs] (/snapshot/gitlab-ci-local/node_modules/yargs/yargs.js:1182:35)
    at Object.get [as argv] (/snapshot/gitlab-ci-local/node_modules/yargs/yargs.js:1088:21)
    at Object.<anonymous> (/snapshot/gitlab-ci-local/dist/index.js)
    at Module._compile (pkg/prelude/bootstrap.js:1320:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)

**Comment by firecow** [comment]
I don't know how on earth that would ever become empty. But i'll implement a check for it

**Comment by firecow** [comment]
@moberghammer I don't know if this is actually fixed. But I'm closing this, since I haven't heard any complains the last 2 months.
We can always open a new open, if the problem reappears.
