### ISSUE TITLE
docker:dind service failure

### ISSUE THREAD

**Issue by niki9796dk** [firecow/gitlab-ci-local#301]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
stages:
  - build

build-dev:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com
```

**Expected behavior**
https://gitlab.com/niki9796dk/gitlab-ci-local-debugging/-/jobs/1731462426

**Host information**
Ubuntu 20.04.2 LTS
gitlab-ci-local 4.25.1

**Additional context**
gitlab ci local console dump
```
parsing and downloads finished in 55 ms
build               starting docker:latest (build)
build               pulled docker:latest in 61 ms
build               pulled docker:dind in 66 ms
build               started service image: docker:dind with aliases: docker, docker in 567 ms
build               copied to container in 1.36 s
build               copied artifacts to container in 1.91 s
build               $ docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com
build               > WARNING! Using --password via the CLI is insecure. Use --password-stdin.
build               > still running...
build               > error during connect: Post "http://docker:2375/v1.24/auth": dial tcp: lookup docker: Try again
build               finished in 26 s  FAIL 1  

 FAIL  build  
```

**Comment by firecow** [comment]
This is most likely todo with missing healthchecking

**Comment by ryall** [comment]
I'm seeing the same, I think:

```
build_image $ docker build . -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
build_image > time="2021-11-07T15:30:19Z" level=error msg="failed to dial gRPC: cannot connect to the Docker daemon. Is 'docker daemon' running on this host?: dial tcp: lookup docker on 127.0.0.11:53: no such host"
build_image > error during connect: Post http://docker:2375/v1.40/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&session=redacted&shmsize=0&t=registry.gitlab.com%2Fredacted%3Adev&target=&ulimits=null&version=1: dial tcp: lookup docker on 127.0.0.11:53: no such host
build_image > time="2021-11-07T15:30:19Z" level=error msg="Can't add file /builds/build_image/package.json to tar: io: read/write on closed pipe"
build_image > time="2021-11-07T15:30:19Z" level=error msg="Can't close tar writer: io: read/write on closed pipe"
build_image finished in 5.77 s  FAIL 1
```

**Comment by firecow** [comment]
We need a way to print docker logs, from the service container, when/if it exits

**Comment by firecow** [comment]
```
Using docker image sha256:5261796049dd8a51b9e1c9ab5fa3e06960de7a813e7414dcc218022a6eb48680 for docker:dind with digest docker@sha256:79d0c6e997920e71e96571ef434defcca1364d693d5b937232decf1ee7524a9b ...
Waiting for services to be up and running...
*** WARNING: Service runner-cpur9s9m-project-1112-concurrent-0-837688e84707049f-docker-0 probably didn't start properly.
Health check error:
service "runner-cpur9s9m-project-1112-concurrent-0-837688e84707049f-docker-0-wait-for-service" timeout
Health check container logs:
Service container logs:
2021-11-20T15:06:49.994056878Z Generating RSA private key, 4096 bit long modulus (2 primes)
2021-11-20T15:06:50.569899551Z ..................................................................................................................++++
2021-11-20T15:06:50.851103256Z ........................................................++++
2021-11-20T15:06:50.851578048Z e is 65537 (0x010001)
2021-11-20T15:06:50.869248748Z Generating RSA private key, 4096 bit long modulus (2 primes)
2021-11-20T15:06:51.310935919Z .........................................................................................++++
2021-11-20T15:06:51.689547985Z ............................................................................++++
2021-11-20T15:06:51.690035812Z e is 65537 (0x010001)
2021-11-20T15:06:51.725196492Z Signature ok
2021-11-20T15:06:51.725223903Z subject=CN = docker:dind server
2021-11-20T15:06:51.725416966Z Getting CA Private Key
2021-11-20T15:06:51.739732462Z /certs/server/cert.pem: OK
2021-11-20T15:06:51.743761151Z Generating RSA private key, 4096 bit long modulus (2 primes)
2021-11-20T15:06:51.800659171Z .........++++
2021-11-20T15:06:52.292892539Z ...................................................................................................++++
2021-11-20T15:06:52.293391216Z e is 65537 (0x010001)
2021-11-20T15:06:52.323573101Z Signature ok
2021-11-20T15:06:52.323587769Z subject=CN = docker:dind client
2021-11-20T15:06:52.323836386Z Getting CA Private Key
2021-11-20T15:06:52.338583503Z /certs/client/cert.pem: OK
2021-11-20T15:06:52.385231155Z mount: permission denied (are you root?)
2021-11-20T15:06:52.385319060Z Could not mount /sys/kernel/security.
2021-11-20T15:06:52.385349718Z AppArmor detection and --privileged mode might break.
2021-11-20T15:06:52.386727817Z mount: permission denied (are you root?)
*********
```
@niki9796dk This is what I'm seeing on our private gitlab.

Where have you seen the pasted example work?

**Comment by firecow** [comment]
I've investigated a little further... 
docker-privileged is definitely needed in `.gitlab-ci-local-env` or via `--privileged`

**Comment by firecow** [comment]
And `DOCKER_TLS=""` probably also need to be there somewhere. Unless you want TLS enabled..
https://docs.gitlab.com/ee/ci/docker/using_docker_build.html

Whats going on here is probably just @niki9796dk running on gitlab.com, where all this is taken care off in advance.

**Comment by ryall** [comment]
I would test it but I have already solved the issue by switching from DinD to Kaniko [as explained in the Gitlab docs](https://docs.gitlab.com/ee/ci/docker/using_kaniko.html).

**Comment by HeWhoWas** [comment]
I had a similar issue, and found sleeping for 10 seconds before running my script ensured that docker would be available. A better solution would be to use something like `wait-for-it.sh` to do the same, or implement healthchecks within gitlab-local-ci.

**Comment by HeWhoWas** [comment]
I've settled on:

- Putting `wait-for-it.sh` into the repository
- Using something like the following:
```
ct-install:
  stage: test

  services:
    - docker:dind

  variables:
    DOCKER_HOST: tcp://docker:2375

  before_script:
    - WAIT_PORT=$(echo "${DOCKER_HOST}" | sed 's/tcp:\/\/docker://g' )
    - .gitlab-ci/wait-for-it.sh -h docker -p "${WAIT_PORT}"
  script:
    - ...
```

**Comment by firecow** [comment]
@HeWhoWas Yeah, we just need to figure out how gitlab's builtin "wait-for" is working, and replicate that in gitlab-ci-local

**Comment by firecow** [comment]
```---
stages:
  - build

build-dev:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com
```
Works now.
![image](https://user-images.githubusercontent.com/973602/143861505-3045d190-c0aa-4915-8cde-5ca11669e9ff.png)

**Comment by bcouetil** [comment]
I'm trying to do the same, privileged, but with a docker build, and it fails... I get **Cannot connect to the Docker daemon at tcp://docker:2375. Is the docker daemon running?**

I'm on Ubuntu 18.

```yaml
stages:
  - build

build-dev:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker build -t image:tag backend/casting
```

```
parsing and downloads finished in 48 ms
build-dev starting docker:latest (build)
build-dev pulled docker:latest in 241 ms
build-dev pulled docker:dind in 199 ms
build-dev started service image: docker:dind with aliases: docker in 538 ms
build-dev service image: docker:dind healthcheck passed: docker:2375 in 398 ms
build-dev service image: docker:dind healthcheck passed: docker:2376 in 423 ms
build-dev > still running...
build-dev copied to container in 12 s
build-dev $ docker build -t image:tag backend/casting
build-dev > Cannot connect to the Docker daemon at tcp://docker:2375. Is the docker daemon running?
build-dev finished in 16 s  FAIL 1  

 FAIL  build-dev
  > Cannot connect to the Docker daemon at tcp://docker:2375. Is the docker daemon running?
pipeline finished in 22 s
```

**Comment by bcouetil** [comment]
It's just a racing condition. I added 2 seconds lag, and now it works.

Using this in before script : 

`if [ "$GITLAB_CI" = "false" ]; then sleep 2; fi`

Feel free to close if it's OK.

**Comment by firecow** [comment]
But why isn't our healthchecks preventing the racecondition?

**Comment by bcouetil** [comment]
It's just that gcl is a bit faster that a real runner. Gitlab works the same way, only waiting for the port to be available, even if the server is not yet ready.

I've seen official issues about this in the past 🤷

**Comment by lcswillems** [comment]
It still get the error:

```
error during connect: Post "http://docker:2375/v1.24/auth": dial tcp: lookup docker: Try again
```

I tried added a `sleep` at the end of my before_script but without success.

I am just try to push an image to a repository.

**Comment by lcswillems** [comment]
> if [ "$GITLAB_CI" = "false" ]; then sleep 2; fi

@bcouetil I also tried your fix but it doesn't work for me. Is it the only you changed to make it work?

**Comment by lcswillems** [comment]
I found how to fix the error:

```
gitlab-ci-local --shell-isolation --privileged --volume /var/run/docker.sock:/var/run/docker.sock
```

**Comment by bcouetil** [comment]
Yes... but no :sweat_smile: you should not mount docker.sock, or you would probably use your underlying docker instance without knowing.

As advised in the [documentation](https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#docker-in-docker-with-tls-disabled-in-the-docker-executor), you should use both docker variables :

```yaml
docker-build:
  stage: build
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - if [ "$GITLAB_CI" = "false" ]; then sleep 2; fi
    - docker info
  script:
    - docker build -f $MODULE/Dockerfile -t $IMAGE_NAME:$CI_PIPELINE_ID $DOCKER_WORKING_FOLDER
 ```
 
 Then the only command line option needed is `gitlab-ci-local --privileged`

**Comment by lcswillems** [comment]
When I try this `.gitlab-ci.yml`:

```
stages:
  - build

docker-build:
  stage: build
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - if [ "$GITLAB_CI" = "false" ]; then sleep 2; fi
    - docker info
  script:
    - echo 'hi'
```

I get this error:

```
parsing and downloads finished in 54 ms
docker-build starting docker:19.03.12 (build)
docker-build pulled docker:19.03.12 in 2.77 s
docker-build pulled docker:19.03.12-dind in 33 ms
Error: Command failed with exit code 1: docker create -u 0:0 -i --network gitlab-ci-local-474466 --privileged --network-alias=docker -e DOCKER_HOST -e DOCKER_TLS_CERTDIR -e GITLAB_USER_LOGIN -e GITLAB_USER_EMAIL -e GITLAB_USER_NAME -e GITLAB_USER_ID -e CI_COMMIT_SHORT_SHA -e CI_COMMIT_SHA -e CI_PROJECT_DIR -e CI_PROJECT_NAME -e CI_PROJECT_TITLE -e CI_PROJECT_PATH -e CI_PROJECT_PATH_SLUG -e CI_PROJECT_NAMESPACE -e CI_PROJECT_VISIBILITY -e CI_PROJECT_ID -e CI_COMMIT_REF_PROTECTED -e CI_COMMIT_BRANCH -e CI_COMMIT_REF_NAME -e CI_COMMIT_REF_SLUG -e CI_COMMIT_TITLE -e CI_COMMIT_MESSAGE -e CI_COMMIT_DESCRIPTION -e CI_PIPELINE_SOURCE -e CI_JOB_ID -e CI_PIPELINE_ID -e CI_PIPELINE_IID -e CI_SERVER_HOST -e CI_SERVER_PORT -e CI_SERVER_URL -e CI_SERVER_PROTOCOL -e CI_API_V4_URL -e CI_PROJECT_URL -e CI_JOB_URL -e CI_PIPELINE_URL -e CI_JOB_NAME -e CI_JOB_STAGE -e CI_REGISTRY -e CI_REGISTRY_IMAGE -e GITLAB_CI -e CI_ENVIRONMENT_NAME -e CI_ENVIRONMENT_SLUG -e CI_ENVIRONMENT_URL -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -e AWS_DEFAULT_REGION -e CLOUDFLARE_API_TOKEN -e ENV_FILE -e TF_VAR_BACKEND_DOMAIN_NAME -e TF_VAR_FRONTEND_DOMAIN_NAME docker:19.03.12-dind 
error during connect: Post "http://docker:2375/v1.24/containers/create": dial tcp: lookup docker: Temporary failure in name resolution
    at makeError (/home/lcswillems/.nvm/versions/node/v16.15.0/lib/node_modules/gitlab-ci-local/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/home/lcswillems/.nvm/versions/node/v16.15.0/lib/node_modules/gitlab-ci-local/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Job.startService (/home/lcswillems/.nvm/versions/node/v16.15.0/lib/node_modules/gitlab-ci-local/src/job.ts:939:39)
    at Job.execScripts (/home/lcswillems/.nvm/versions/node/v16.15.0/lib/node_modules/gitlab-ci-local/src/job.ts:532:41)
    at Job.start (/home/lcswillems/.nvm/versions/node/v16.15.0/lib/node_modules/gitlab-ci-local/src/job.ts:363:36)
```

**Comment by bergpb** [comment]
I'm facing a similar error here:
```
gitlab-ci-local --privileged                                                                     
parsing and downloads finished in 68 ms
lint  starting hadolint/hadolint:v2.12.0-alpine (lint)
lint  copied to docker volumes in 972 ms
lint  $ hadolint Dockerfile
lint  finished in 1.95 s
build starting docker:stable (build)
build copied to docker volumes in 997 ms
build started service image: docker:23-dind with aliases: docker in 658 ms
build > still running...
build service image: docker:23-dind healthcheck passed in 10 s
build $ docker build -f Dockerfile -t $CONTAINER_TEST_IMAGE --no-cache .
build > Cannot connect to the Docker daemon at tcp://docker:2375. Is the docker daemon running?
build finished in 13 s  FAIL 1  

 PASS  lint 
 FAIL  build
  > Cannot connect to the Docker daemon at tcp://docker:2375. Is the docker daemon running?
pipeline finished in 15 s
```

Checking the dind service logs, seems like the dind service starts using in a different port:
```
|   time="2023-04-28T00:01:49.563544322Z" level=info msg="Docker daemon" commit=cbce331 graphdriver=overlay2 version=23.0.4                                                                                                                                                                                                   
│   time="2023-04-28T00:01:49.563728214Z" level=info msg="Daemon has completed initialization"                                                                                                                                                                                                                                
│   time="2023-04-28T00:01:49.637008634Z" level=info msg="[core] [Server #10] Server created" module=grpc                                                                                                                                                                                                                    
│   time="2023-04-28T00:01:49.642883188Z" level=info msg="API listen on [::]:2376"                                                                                                                                                                                                                                            
│   time="2023-04-28T00:01:49.652717886Z" level=info msg="API listen on /var/run/docker.sock"
```

Here my build step:
```
build:
  stage: build
  image: docker:stable
  services:
    - docker:23-dind
  script:
    - docker build -f Dockerfile -t $CONTAINER_TEST_IMAGE --no-cache .
    - docker push $CONTAINER_TEST_IMAGE
```

**Comment by firecow** [comment]
https://github.com/firecow/gitlab-ci-local/tree/master/examples/docker-in-docker-build
