### ISSUE TITLE
SyntaxError: Unexpected token '?'

### ISSUE THREAD

**Issue by 4n70w4** [firecow/gitlab-ci-local#519]
```bash
sudo npm install -g gitlab-ci-local
```

```
/usr/bin/gitlab-ci-local -> /usr/lib/node_modules/gitlab-ci-local/src/index.js
npm WARN notsup Unsupported engine for gitlab-ci-local@4.32.0: wanted: {"node":">=16.10.0"} (current: {"node":"12.22.12","npm":"6.14.16"})
npm WARN notsup Not compatible with your version of node/npm: gitlab-ci-local@4.32.0

+ gitlab-ci-local@4.32.0
added 62 packages from 78 contributors in 4.09s
```

```bash
gitlab-ci-local
```

```bash
/usr/lib/node_modules/gitlab-ci-local/src/parser.js:123
            const parallelMatrixVariablesList = parallel.matrixVariablesList(jobData, jobName) ?? [null];
                                                                                                ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/lib/node_modules/gitlab-ci-local/src/index.ts:7:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

**Comment by firecow** [comment]
You need nodejs18
