### ISSUE TITLE
env type File don't work

### ISSUE THREAD

**Issue by NuVivo314** [firecow/gitlab-ci-local#607]
Hello. 

On my desk, the File ENV feature don't work. 

Docker throw error 

**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
job:
  script:
    - echo "Heya"
    - cat $ENV_FILE
```

```yaml
---
project:
  gitlab.com/example/example.git:
    VAULT_ADDR: https://vault.example.io
    VAULT_SERVER_URL: https://vault.example.io
    ENV_FILE: '~/tmp/.env'
```

this work if i remove ENV_FILE. 

out
```shell
Error: Command failed with exit code 1: docker cp /tmp/gitlab-ci-local-file-variables-company-company-278504 e283d2b610ca666b1e3a65bc7912520ddcfeb4e9fc31402dd1e9e8a05dd8923a:/tmp/gitlab-ci-local-file-variables-company-company-278504/
Error: No such container:path: e283d2b610ca666b1e3a65bc7912520ddcfeb4e9fc31402dd1e9e8a05dd8923a:/tmp
    at makeError (/usr/lib/node_modules/gitlab-ci-local/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/usr/lib/node_modules/gitlab-ci-local/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Job.startService (/usr/lib/node_modules/gitlab-ci-local/src/job.ts:988:13)
    at Job.execScripts (/usr/lib/node_modules/gitlab-ci-local/src/job.ts:536:48)
    at Job.start (/usr/lib/node_modules/gitlab-ci-local/src/job.ts:367:36)

```
**Host information**
Archlinux
gitlab-ci-local 4.33.1
Docker version 20.10.18, build b40c2f6b5d

**Comment by firecow** [comment]
You mean
```
$GITLAB_CI_LOCAL_CONFIG_ENV = $HOME/.gitlab-ci-local-variables.yml
```
instead of 
```
$GITLBA_CI_LOCAL_CONFIG_ENV = $HOME/.gitlab-ci-local/variables.yml
```

Right ?

**Comment by firecow** [comment]
I cannot reproduce this at all.
No matter what conditions I try, i can't seem to match yours.

I would suggest that you create a completely new project, and try to provide us with an as small as possible way of reproducing.

Feel free to reopen.
