### ISSUE TITLE
Cannot connect du Docker daemon with Rancher Desktop under MacOS for M1

### ISSUE THREAD

**Issue by bcouetil** [firecow/gitlab-ci-local#659]
Hey ! I did not write any issue on this wonderful tool for a long time, I had to 🥰

I'm migrating to a Mac M1 (Macbook Pro 16). I installed Rancher Desktop to have Docker and Kubernetes without Docker Desktop.

Docker is working fine. At least for any command I tried.

But any pipeline under gitlab-ci-local will give me this error :

`Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`

I tried mounting the docker.sock or not with the volume option. Always the same result.

In which direction should I dig to troubleshoot ?

**Minimal .gitlab-ci.yml illustrating the issue**
```yml
remove-me:
  image: alpine:3
  script:
    - env | sort
```

**Expected behavior**
Paste a public job url.

**Host information**
MacOS 12.x M1
gitlab-ci-local 4.34

**Additional context**

**Comment by firecow** [comment]
Pretty sure this has nothing with GCL to do 😁

`/run/docker.sock` is no where in the source.

**Comment by bcouetil** [comment]
I think that is because GCL uses `execa` and it does not follow aliases : https://github.com/sindresorhus/execa/issues/100

I'll have to explore other solutions than Rancher Desktop.

Is there anyone here using MacOS without the (not free anymore) Docker Desktop ?

**Comment by bcouetil** [comment]
Hum nevermind, it is a symlink, not an alias.

But my question is still valid 😓

**Comment by firecow** [comment]
So `which docker` points to to `/usr/local/bin/docker` and `/usr/local/bin/docker` is a symlink ?

**Comment by firecow** [comment]
`testhest.sh`
```
#!/usr/bin/env bash

echo "Testhest"
```

Create a symlink
```
ln -s testhest.sh symlink.sh
```

`index.js`
```
import execa from "execa"

(async () => {
    const res = await execa("./symlink.sh", {all: true});
    console.log(res.all);
})();

```

Output
```
mjn@mjn-laptop:~/workspace/firecow-gitlab-ci-local$ node index.mjs
Testhest
```

I'm pretty sure, execa can do symlinks :smile:

**Comment by bcouetil** [comment]
Thank you for your time my friend 😊 

We are progressing thanks to your inputs.

I'm giving more context.

Details on the error

```shell
gl ☸✨-statics-mr
parsing and downloads finished in 234 ms
☸✨-statics-mr                             starting alpine/k8s:1.22.13 (☸ deploy dependencies)
Error: Command failed with exit code 1: docker create --privileged -u 0:0 -i  --volume gcl-4pi44pyo-statics-mr-918545-build:/gcl-builds --volume gcl-4pi44pyo-statics-mr-918545-tmp:/tmp/ --workdir /gcl-builds -e FF_USE_NEW_SHELL_ESCAPE -e FF_USE_DYNAMIC_TRACE_FORCE_SEND_INTERVAL -e FF_USE_FASTZIP -e ARTIFACT_COMPRESSION_LEVEL -e CACHE_COMPRESSION_LEVEL -e DOCKERFILE -e MODULE -e TIER_FOLDER -e DOCKER_IMAGE -e CORE_INGRESS_DOMAIN -e INGRESS_DOMAIN -e DOCKER_IMAGE_DATA -e ENV -e BACKEND_KEYS_ISSUER -e PLEENK_CERTIFICATE_ISSUER -e GITLAB_USER_LOGIN -e GITLAB_USER_EMAIL -e GITLAB_USER_NAME -e GITLAB_USER_ID -e CI_COMMIT_SHORT_SHA -e CI_COMMIT_SHA -e CI_PROJECT_DIR -e CI_PROJECT_NAME -e CI_PROJECT_TITLE -e CI_PROJECT_PATH -e CI_PROJECT_PATH_SLUG -e CI_PROJECT_NAMESPACE -e CI_PROJECT_VISIBILITY -e CI_PROJECT_ID -e CI_COMMIT_REF_PROTECTED -e CI_COMMIT_BRANCH -e CI_COMMIT_REF_NAME -e CI_COMMIT_REF_SLUG -e CI_COMMIT_TITLE -e CI_COMMIT_MESSAGE -e CI_COMMIT_DESCRIPTION -e CI_PIPELINE_SOURCE -e CI_JOB_ID -e CI_PIPELINE_ID -e CI_PIPELINE_IID -e CI_SERVER_HOST -e CI_SERVER_PORT -e CI_SERVER_URL -e CI_SERVER_PROTOCOL -e CI_API_V4_URL -e CI_PROJECT_URL -e CI_JOB_URL -e CI_PIPELINE_URL -e CI_JOB_NAME -e CI_JOB_STAGE -e CI_REGISTRY -e CI_REGISTRY_IMAGE -e GITLAB_CI -e CI_ENVIRONMENT_NAME -e CI_ENVIRONMENT_SLUG -e CI_ENVIRONMENT_URL -e CI_NODE_INDEX -e CI_NODE_TOTAL -e PLEENK_REGISTRY -e PLEENK_REGISTRY_USER -e PLEENK_REGISTRY_PASSWORD -e CI_MERGE_REQUEST_ID -e CI_JOB_TOKEN -e CI_MERGE_REQUEST_PROJECT_URL -e DOCKER_HOST -e DOCKER_AUTH_CONFIG -e KUBECONFIG -e CI_JOB_STATUS alpine/k8s:1.22.13 sh -c "
if [ -x /usr/local/bin/bash ]; then
        exec /usr/local/bin/bash 
elif [ -x /usr/bin/bash ]; then
        exec /usr/bin/bash 
elif [ -x /bin/bash ]; then
        exec /bin/bash 
elif [ -x /usr/local/bin/sh ]; then
        exec /usr/local/bin/sh 
elif [ -x /usr/bin/sh ]; then
        exec /usr/bin/sh 
elif [ -x /bin/sh ]; then
        exec /bin/sh 
elif [ -x /busybox/sh ]; then
        exec /busybox/sh 
else
        echo shell not found
        exit 1
fi
"
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
    at makeError (/opt/homebrew/Cellar/gitlab-ci-local/4.34.0/libexec/lib/node_modules/gitlab-ci-local/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/opt/homebrew/Cellar/gitlab-ci-local/4.34.0/libexec/lib/node_modules/gitlab-ci-local/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Job.execScripts (/opt/homebrew/Cellar/gitlab-ci-local/4.34.0/libexec/lib/node_modules/gitlab-ci-local/src/job.ts:604:43)
    at Job.start (/opt/homebrew/Cellar/gitlab-ci-local/4.34.0/libexec/lib/node_modules/gitlab-ci-local/src/job.ts:377:36)
```

My docker commands are working, in the same shell session right after :

```shell
➜  mono-pleenk git:(207-ci-stern) docker ps -a                                                                                                               dev@cloud/develop
CONTAINER ID   IMAGE                  COMMAND                  CREATED      STATUS      PORTS     NAMES
64b29347daf1   fe8bc53de6e4           "local-path-provisio…"   4 days ago   Up 4 days             k8s_local-path-provisioner_local-path-provisioner-7b7dc8d6f5-glvx8_kube-system_0a2c8a16-9ff9-4cb3-ab3d-cd6955bcd039_15
7f38695bd42d   k8s.gcr.io/pause:3.6   "/pause"                 4 days ago   Up 4 days             k8s_POD_local-path-provisioner-7b7dc8d6f5-glvx8_kube-system_0a2c8a16-9ff9-4cb3-ab3d-cd6955bcd039_11
8eb8cf144dbf   f40c41555cd4           "/coredns -conf /etc…"   4 days ago   Up 4 days             k8s_coredns_coredns-b96499967-ql8br_kube-system_f72fd096-871f-44e2-8006-8218f6418faa_11
92975888d749   k8s.gcr.io/pause:3.6   "/pause"                 4 days ago   Up 4 days             k8s_POD_coredns-b96499967-ql8br_kube-system_f72fd096-871f-44e2-8006-8218f6418faa_11
```

But docker is an alias to an app with a parameter :

```shell
➜  mono-pleenk git:(207-ci-stern) whereis docker
docker: /Users/bcouetil/.rd/bin/docker

➜  mono-pleenk git:(207-ci-stern) ls -ll /Users/bcouetil/.rd/bin/docker
lrwxr-xr-x  1 bcouetil  staff  80  3 Nov 20:28 /Users/bcouetil/.rd/bin/docker -> /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/bin/docker
```


So my question is more : how can i pin-point the problem, since docker seems to work in shell ?

**Comment by firecow** [comment]
Hit me up with a printenv stripped of all "secrets" 😁

**Comment by bcouetil** [comment]
Oh man I know you would help me !

I removed env variables one by one in `variables.yml`, and this one was messing up :

```
DOCKER_HOST: ""
```

I blindly took all my variables from Ubuntu. My bad.

Now it works like a charm on my Macbook Pro M1 🎉🤗💪🙏

**Comment by firecow** [comment]
I'm awesome :smile:
