### ISSUE TITLE
Docker API not reachable after install

### ISSUE THREAD

**Issue by Guits32** [firecow/gitlab-ci-local#911]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
test:
  script:
    - echo "Hello world!"
```

**Expected behavior**
Document needed docker configuration to open tcp socket 2375.

**Host information**
Debian 11
gitlab-ci-local 4.41.2
Docker version 24.0.2, build cb74dfc
Node version: v18.16.1

**Additional context**

Installation done with npm.

If I start gitlab-ci-local without any docker daemon configuration, I have this issue:
``` shell
Cannot connect to the Docker daemon at tcp://docker:2375/. Is the docker daemon running?
```

Full trace:
``` shell
Error: Command failed with exit code 1: docker create --interactive  --user 0:0 --volume gcl-merge-integration-953852-build:/gcl-builds --volume gcl-merge-integration-953852-tmp:/tmp/gitlab-ci-local-file-variables-nora-groot-953852 --workdir /gcl-builds -e YAML_IMAGE -e SHELL_IMAGE -e DOCKER_HOST -e DOCKER_DRIVER -e DOCKER_REGISTRY -e DOCKER_TLS_CERTDIR -e RELEASE_MONITOR_BASE_URL -e APPS_DIR -e FACE_DIR -e MOSAIC_DIR -e VISION_DIR -e GIT_SSH_COMMAND -e RELEASE_MONITOR_PIPELINE_NAME -e COMPONENT_LIST -e GIT_STRATEGY -e GITLAB_USER_LOGIN -e GITLAB_USER_EMAIL -e GITLAB_USER_NAME -e GITLAB_USER_ID -e CI_COMMIT_SHORT_SHA -e CI_COMMIT_SHA -e CI_PROJECT_NAME -e CI_PROJECT_TITLE -e CI_PROJECT_PATH -e CI_PROJECT_PATH_SLUG -e CI_PROJECT_NAMESPACE -e CI_PROJECT_VISIBILITY -e CI_PROJECT_ID -e CI_COMMIT_REF_PROTECTED -e CI_COMMIT_BRANCH -e CI_COMMIT_REF_NAME -e CI_COMMIT_REF_SLUG -e CI_COMMIT_TITLE -e CI_COMMIT_MESSAGE -e CI_COMMIT_DESCRIPTION -e CI_PIPELINE_SOURCE -e CI_SERVER_HOST -e CI_SERVER_PORT -e CI_SERVER_URL -e CI_SERVER_PROTOCOL -e CI_API_V4_URL -e CI_PROJECT_URL -e GITLAB_CI -e CI_JOB_ID -e CI_PIPELINE_ID -e CI_PIPELINE_IID -e CI_JOB_NAME -e CI_JOB_NAME_SLUG -e CI_JOB_STAGE -e CI_PROJECT_DIR -e CI_JOB_URL -e CI_PIPELINE_URL -e CI_ENVIRONMENT_NAME -e CI_ENVIRONMENT_SLUG -e CI_ENVIRONMENT_URL -e CI_NODE_INDEX -e CI_NODE_TOTAL -e CI_REGISTRY -e CI_REGISTRY_IMAGE -e CHAT_WEBHOOK_URL -e NEXUS_USERNAME -e NEXUS_PASSWORD -e ANSIBLE_VAULT_PASSWORD -e SSH_PRIVATE_KEY -e BRIGIT_ACCESS_TOKEN -e GIT_SSH_PRIVATE_KEY -e MATTERMOST_CHANNEL -e DOCKER_AUTH_CONFIG -e CI_JOB_STATUS  d.i-run.fr/irun-compiler:jdk8-20230111.89d4ad2b sh -c "
if [ -x /usr/local/bin/bash ]; then
	exec /usr/local/bin/bash 
elif [ -x /usr/bin/bash ]; then
	exec /usr/bin/bash 
elif [ -x /bin/bash ]; then
	exec /bin/bash 
elif [ -x /usr/local/bin/sh ]; then
	exec /usr/local/bin/sh 
elif [ -x /usr/bin/sh ]; then
	exec /usr/bin/sh 
elif [ -x /bin/sh ]; then
	exec /bin/sh 
elif [ -x /busybox/sh ]; then
	exec /busybox/sh 
else
	echo shell not found
	exit 1
fi
"
Cannot connect to the Docker daemon at tcp://docker:2375/. Is the docker daemon running?
    at makeError (/home/gaufrere/.nvm/versions/node/v18.16.1/lib/node_modules/gitlab-ci-local/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/home/gaufrere/.nvm/versions/node/v18.16.1/lib/node_modules/gitlab-ci-local/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Job.execScripts (/home/gaufrere/.nvm/versions/node/v18.16.1/lib/node_modules/gitlab-ci-local/src/job.ts:691:43)
    at Job.start (/home/gaufrere/.nvm/versions/node/v18.16.1/lib/node_modules/gitlab-ci-local/src/job.ts:458:36)
    at async Promise.all (index 2)
    at Function.runLoop (/home/gaufrere/.nvm/versions/node/v18.16.1/lib/node_modules/gitlab-ci-local/src/executor.ts:17:13)
    at Function.runPipeline (/home/gaufrere/.nvm/versions/node/v18.16.1/lib/node_modules/gitlab-ci-local/src/commander.ts:20:9)
    at handler (/home/gaufrere/.nvm/versions/node/v18.16.1/lib/node_modules/gitlab-ci-local/src/handler.ts:132:9)
    at Object.handler (/home/gaufrere/.nvm/versions/node/v18.16.1/lib/node_modules/gitlab-ci-local/src/index.ts:25:34)
```
To solve it, I have to do the following docker daemon config:
``` shell 
$ - cat daemon.json.backup 
{
	"storage-driver": "overlay2",
	"hosts": [
		"tcp://127.0.0.1:2375",
		"unix:///var/run/docker.sock"
	]
}
```

And add a redirection in my `/etc/hosts`:
``` shell 
$ - cat /etc/hosts
127.0.0.1	docker
```

May be I missed something in the installation process. If not, it would be great to document it.

**Comment by firecow** [comment]
Hmmm....

It seems like something was just "off" in your docker setup, and you corrected it by editing the docker daemon.json.

I'm fairly certain this has nothing to do with gitlab-ci-local.
