### ISSUE TITLE
Specifying `CONCURRENCY` in `.gitlab-ci-local-env` fails with '"concurrency" must be a number'

### ISSUE THREAD

**Issue by wdconinc** [firecow/gitlab-ci-local#969]
**Minimal .gitlab-ci.yml illustrating the issue**
Not really an issue with a specific `.gitlab-ci.yml`...
```console
19:03:08 wdconinc@menelaos ~/EIC/containers/eic_container (push-when-needed *$%=) $ cat .gitlab-ci-local-env
CONCURRENCY=1
19:03:12 wdconinc@menelaos ~/EIC/containers/eic_container (push-when-needed *$%=) $ gitlab-ci-local
parsing and downloads finished in 89 ms
Error: "concurrency" must be a number, 1 or up. Received "1" (string)
    at Function.createFrom (/snapshot/firecow-gitlab-ci-local/node_modules/@supercharge/promise-pool/dist/validation-error.js:20:16)
    at PromisePoolExecutor.useConcurrency (/snapshot/firecow-gitlab-ci-local/node_modules/@supercharge/promise-pool/dist/promise-pool-executor.js:38:54)
    at PromisePool.process (/snapshot/firecow-gitlab-ci-local/node_modules/@supercharge/promise-pool/dist/promise-pool.js:134:14)
    at Function.runLoop (/snapshot/firecow-gitlab-ci-local/src/executor.ts:18:22)
    at Function.runPipeline (/snapshot/firecow-gitlab-ci-local/src/commander.ts:20:24)
    at handler (/snapshot/firecow-gitlab-ci-local/src/handler.ts:132:25)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.handler (/snapshot/firecow-gitlab-ci-local/src/index.ts:25:34)
19:03:18 wdconinc@menelaos ~/EIC/containers/eic_container (push-when-needed *$%=) $ gitlab-ci-local --version
4.42.0
```

**Expected behavior**
I had expected that this would behave as `gitlab-ci-local --concurrency 1` (similar to how `PRIVILEGED` is interpreted as such). Concurrency does work fine:
```console
19:03:21 wdconinc@menelaos ~/EIC/containers/eic_container (push-when-needed *$%=) $ gitlab-ci-local --concurrency 1
parsing and downloads finished in 92 ms
version                                                                    starting alpine:latest (config)
version                                                                    copied to docker volumes in 1.19 s
version                                                                    $ if [ -n "${VERSION}" ]; then # collapsed multi-line command
version                                                                    > INTERNAL_TAG=pipeline-1083
version                                                                    > VERSION=push-when-needed-1083
version                                                                    > NIGHTLY_TAG=nightly
version                                                                    > EXPORT_TAG=
version                                                                    exported artifacts in 693 ms
version                                                                    copied artifacts to cwd in 115 ms
version                                                                    finished in 2.66 s
```
(etc)

**Host information**
Ubuntu 23.04
gitlab-ci-local 4.42.0 (from https://gitlab-ci-local-ppa.firecow.dk)

**Comment by firecow** [comment]
All non-string CLI/env options suffers from this problem.
