### ISSUE TITLE
collapsed before_script  failing

### ISSUE THREAD

**Issue by wgoetz** [firecow/gitlab-ci-local#978]
**Failure Output**

Using fallback git commit data
TypeError: job.beforeScripts.forEach is not a function
    at Function.arrayOfStrings (/usr/local/Cellar/gitlab-ci-local/4.43.0/libexec/lib/node_modules/gitlab-ci-local/src/validator.ts:76:31)
    at Function.run (/usr/local/Cellar/gitlab-ci-local/4.43.0/libexec/lib/node_modules/gitlab-ci-local/src/validator.ts:85:14)
    at Function.create (/usr/local/Cellar/gitlab-ci-local/4.43.0/libexec/lib/node_modules/gitlab-ci-local/src/parser.ts:55:42)
    at handler (/usr/local/Cellar/gitlab-ci-local/4.43.0/libexec/lib/node_modules/gitlab-ci-local/src/handler.ts:96:18)
    at Object.handler (/usr/local/Cellar/gitlab-ci-local/4.43.0/libexec/lib/node_modules/gitlab-ci-local/src/index.ts:36:21)

**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
printvar:
  stage: build
  before_script: |
    echo before
  script: |
    echo script
```

**Expected behavior**
not crashing, should output 'before' 

**Host information**
installed on MacOs via brew, ubuntu 2204 via apt

**Quick fix**
do not use
```yml
  before_script: |
    command1
    command2
```
instead write commands step-by-step
```yml 
  before_script:
   - command1
   - command2
```

**Comment by firecow** [comment]
`before_script:` must be an array.
https://docs.gitlab.com/ee/ci/yaml/#before_script 

`script:` must be an array of strings or a string
https://docs.gitlab.com/ee/ci/yaml/#script
